# Generated by Django 4.2.1 on 2023-05-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentReport',
            fields=[
                ('investment_report_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=45)),
                ('scale', models.CharField(max_length=45)),
                ('point_on_scale', models.DecimalField(decimal_places=0, max_digits=10)),
                ('funded_by', models.CharField(max_length=45)),
                ('annual_salary', models.DecimalField(decimal_places=0, max_digits=10)),
                ('weekly_hours', models.DecimalField(decimal_places=0, max_digits=10)),
                ('gross_weekly', models.DecimalField(decimal_places=0, max_digits=10)),
                ('full_day_rate', models.DecimalField(decimal_places=0, max_digits=10)),
                ('half_day_rate', models.DecimalField(decimal_places=0, max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=0, max_digits=10)),
                ('admin_id', models.CharField(max_length=20)),
                ('evaluation_id', models.CharField(max_length=20)),
                ('employee_id', models.CharField(max_length=20)),
                ('training_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='test_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_id', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
    ]
