# Generated by Django 4.2.1 on 2023-06-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.CharField(max_length=100)),
                ('employee_job_title', models.EmailField(max_length=100)),
                ('length_of_service', models.CharField(max_length=100)),
                ('training_course_name', models.CharField(max_length=100)),
                ('training_course_provider', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=10)),
                ('end_date', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=100)),
                ('number_of_days', models.CharField(max_length=10)),
                ('delivery_method', models.CharField(max_length=50)),
                ('course_aims_and_objectives', models.CharField(max_length=500)),
                ('expected_outcome', models.CharField(max_length=500)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ballymun_job_centre_contribution', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'database_addApp',
            },
        ),
        migrations.CreateModel(
            name='ProgramRegistration',
            fields=[
                ('employee_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employee_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Iaactive'), ('terminated', 'Terminated')], max_length=20)),
                ('funded_by', models.TextField(max_length=45)),
                ('employee_email', models.EmailField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('employee_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=45)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=8)),
                ('position', models.CharField(max_length=45)),
                ('funded_by', models.CharField(max_length=45)),
                ('annual_salary', models.DecimalField(decimal_places=0, max_digits=10)),
                ('is_admin', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
            ],
        ),
    ]
