# Generated by Django 4.2.1 on 2023-05-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePersonalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employee_status', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=255)),
                ('funded_by', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='annual_salary',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default=0, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default=0, max_length=45),
        ),
        migrations.AddField(
            model_name='employee',
            name='funded_by',
            field=models.CharField(default=0, max_length=45),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_admin',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default=0, max_length=45),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='role_name',
            field=models.CharField(default=0, max_length=45),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(default=0, max_length=45),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(default=0, max_length=45),
        ),
    ]
