# Generated by Django 4.2.1 on 2023-06-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingapplication',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='trainingapplication',
            name='denial_status',
        ),
    ]
