# Generated by Django 4.2.1 on 2023-05-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test_table',
            new_name='testtable',
        ),
    ]
