# Generated by Django 4.2.1 on 2023-06-13 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='employee_id',
        ),
    ]
