# Generated by Django 4.2.1 on 2023-06-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='application_status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='current_status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='total_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_hours',
            field=models.IntegerField(null=True),
        ),
    ]
