# Generated by Django 4.2.1 on 2023-06-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_statementchoice'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='statementchoice',
            table='statment_choice',
        ),
    ]
