# Generated by Django 4.2.1 on 2023-06-16 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_evaluation_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertraining',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trainings', to=settings.AUTH_USER_MODEL),
        ),
    ]
