# Generated by Django 4.2.1 on 2023-05-24 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_employeepersonaldetail_programmeregistration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeePersonalDetail',
        ),
        migrations.DeleteModel(
            name='ProgrammeRegistration',
        ),
    ]
