# Generated by Django 4.2.1 on 2023-06-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_trainingapplication_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingapplication',
            name='reason_for_denial',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
