# Generated by Django 4.2.1 on 2023-06-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_customuser_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='no_of_hours',
            field=models.IntegerField(null=True),
        ),
    ]
