# Generated by Django 4.2.1 on 2023-06-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_statementchoice_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='statementchoice',
            table='statement_choice',
        ),
    ]
