# Generated by Django 4.2.1 on 2023-06-16 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_usertraining_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingapplication',
            name='users',
            field=models.ManyToManyField(through='database.UserTraining', to=settings.AUTH_USER_MODEL),
        ),
    ]
