# Generated by Django 4.2.1 on 2023-06-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_trainingapplication_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingapplication',
            name='approval_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='denial_status',
            field=models.BooleanField(null=True),
        ),
    ]
